### ISSUE TITLE
デザイン修正　ポートフォリオを編集する

### ISSUE THREAD

**Issue by Kazuma7** [u-lab/rebuilt#142]
## やること
・戻る←ボタンはいらない気がする
・上辺の「保存」ボタンはポートフォリオと同じ段の左端で
・ポートフォリオを見ると名前boxはもっと幅を狭く
・マテリアルデザイン的に裏に載っている一枚を無くす

**Comment by H37kouya** [comment]
![S__2555913](https://user-images.githubusercontent.com/46477357/80864463-cdf03300-8cbd-11ea-9f0f-65ea6a264ee8.jpg)
