### ISSUE TITLE
デザイン修正　作品追加

### ISSUE THREAD

**Issue by Kazuma7** [u-lab/rebuilt#143]
## やること
・他のページと同じように「新規作品追加」のタイトルを中央揃えで入れる
・タイトルbox、あなたのサイトbox、アイキャッチ画像box、説明boxの端をもう少し空ける

**Comment by H37kouya** [comment]
![S__2555914](https://user-images.githubusercontent.com/46477357/80864198-2a525300-8cbc-11ea-8275-f99040501a65.jpg)
