### ISSUE TITLE
プロフィールを編集(黒須)

### ISSUE THREAD

**Issue by toson77** [u-lab/rebuilt#36]
## URL
/users/profile/edit

**Comment by toson77** [comment]
v-colの内部要素を左右中央ぞろえしたい場合justifyではなくalignを使う
![image](https://user-images.githubusercontent.com/53248281/77047146-9ed07b80-6a07-11ea-9f94-bd41a3d9f99c.png)
![image](https://user-images.githubusercontent.com/53248281/77047266-caebfc80-6a07-11ea-9c89-544b35292cb1.png)

**Comment by H37kouya** [comment]
デザインの構成上不必要になった
