### ISSUE TITLE
作品一覧(黒須)

### ISSUE THREAD

**Issue by toson77** [u-lab/rebuilt#38]
## URL
/strages

**Comment by toson77** [comment]
user.name取れない
vuex mapgettersインポートできてない..?
![image](https://user-images.githubusercontent.com/53248281/76821740-21afd580-6852-11ea-8cc9-0426cf1afc96.png)
![image](https://user-images.githubusercontent.com/53248281/76821755-2ffdf180-6852-11ea-80c8-4ab3c5905f30.png)
![image](https://user-images.githubusercontent.com/53248281/76821804-5ae84580-6852-11ea-9cc9-d2a611dcf635.png)

**Comment by H37kouya** [comment]
## これ書いた？？
```
computed: mapGetters({
  user: 'auth/user'
}),
```

**Comment by toson77** [comment]
かいてませんでしたー

**Comment by toson77** [comment]
なぜか事故ってる
![image](https://user-images.githubusercontent.com/53248281/76854334-3ad87680-6892-11ea-8026-545dfde85145.png)

**Comment by H37kouya** [comment]
apiの方でphp artisan migrate:refresh --seedしたらうまくいかない？

**Comment by toson77** [comment]
{                                                                                                                                                21:09:20
  current_page: 1,
  data: [
    {
      id: 1,
      storage_id: '1581315433ra05d0',
      user_id: 1,
      title: '作品1かっこいいよ',
      description: 'Sapiente inventore voluptate.',
      long_comment: '最近自然の中の曲線や形に興味がある。特にネジバナやサボテンに見られる”螺旋”やバッタの脚を始めとした昆虫の足の曲線が凄く不思議に心が惹か
れる。そこで、そういった自然的な形や線をロボットに入れ込むことで、naturalなロボットを作ることができるのかについて考えた。',
      storage_url: 'http://localhost:8000/storage/storages/example/bunny.obj',
      eyecatch_image_id: '9ae0b301-b7d4-4eed-a150-31b0a9e4f870',
      web_address: 'http://matsumoto.net/similique-dolores-corrupti-quo-et-et-iure-quo-commodi',
      deleted_at: null,
      created_at: '2020-03-17 21:02:39',
      updated_at: '2020-03-17 21:02:39',
      user: [Object],
      eyecatch_image: [Object]
    },
    {
      id: 2,
      storage_id: '1584446559guzl4g',
      user_id: 1,
      title: '作品2かっこいいよ',
      description: 'Nemo animi voluptatem.',
      long_comment: '最近自然の中の曲線や形に興味がある。特にネジバナやサボテンに見られる”螺旋”やバッタの脚を始めとした昆虫の足の曲線が凄く不思議に心が惹か
れる。そこで、そういった自然的な形や線をロボットに入れ込むことで、naturalなロボットを作ることができるのかについて考えた。',
      storage_url: 'http://localhost:8000/storage/storages/example/home_v1.obj',
      eyecatch_image_id: '1d5079ac-4f29-4437-8b53-3747edfd4457',
      web_address: 'https://www.kiriyama.jp/nulla-sunt-quia-repudiandae-inventore-illum',
      deleted_at: null,
      created_at: '2020-03-17 21:02:39',
      updated_at: '2020-03-17 21:02:39',
      user: [Object],
      eyecatch_image: [Object]
    },
    {
      id: 3,
      storage_id: '1584446559vpdbs7',
      user_id: 1,
      title: '作品3かっこいいよ',
      description: 'Necessitatibus qui iure.',
      long_comment: '最近自然の中の曲線や形に興味がある。特にネジバナやサボテンに見られる”螺旋”やバッタの脚を始めとした昆虫の足の曲線が凄く不思議に心が惹か
れる。そこで、そういった自然的な形や線をロボットに入れ込むことで、naturalなロボットを作ることができるのかについて考えた。',
      storage_url: 'http://localhost:8000/storage/storages/example/home_v1.fbx',
      eyecatch_image_id: 'ebf559f5-61c2-43c7-a108-48c5527c4ac8',
      web_address: 'http://sasaki.com/dicta-mollitia-sequi-quaerat-aspernatur-sed.html',
      deleted_at: null,
      created_at: '2020-03-17 21:02:39',
      updated_at: '2020-03-17 21:02:39',
      user: [Object],
      eyecatch_image: [Object]
    },
    {
      id: 4,
      storage_id: '15844465597ezipt',
      user_id: 2,
      title: 'WEBエンジニアの最高傑作',
      description: 'Cum qui quos.',
      long_comment: '最近自然の中の曲線や形に興味がある。特にネジバナやサボテンに見られる”螺旋”やバッタの脚を始めとした昆虫の足の曲線が凄く不思議に心が惹か
れる。そこで、そういった自然的な形や線をロボットに入れ込むことで、naturalなロボットを作ることができるのかについて考えた。',
      storage_url: 'http://localhost:8000/storage/storages/example/ウサギ.stl',
      eyecatch_image_id: '985d085b-0c41-4ee0-b33c-8476bb85d115',
      web_address: 'http://www.koizumi.org/deleniti-quisquam-possimus-illo-enim',
      deleted_at: null,
      created_at: '2020-03-17 21:02:39',
      updated_at: '2020-03-17 21:02:39',
      user: [Object],
      eyecatch_image: [Object]
    },
    {
      id: 5,
      storage_id: '1584446559pwinx2',
      user_id: 3,
      title: 'ニートは頑張れる',
      description: 'Delectus quo laboriosam eligendi.',
      long_comment: '最近自然の中の曲線や形に興味がある。特にネジバナやサボテンに見られる”螺旋”やバッタの脚を始めとした昆虫の足の曲線が凄く不思議に心が惹か
れる。そこで、そういった自然的な形や線をロボットに入れ込むことで、naturalなロボットを作ることができるのかについて考えた。',
      storage_url: 'http://localhost:8000/storage/storages/example/home_v1.stl',
      eyecatch_image_id: 'faf0aa05-8dad-4691-8409-8618b6c8146c',
      web_address: 'http://nishinosono.jp/et-sint-eos-minus-ratione.html',
      deleted_at: null,
      created_at: '2020-03-17 21:02:39',
      updated_at: '2020-03-17 21:02:39',
      user: [Object],
      eyecatch_image: [Object]
    }
  ],
  first_page_url: 'http://localhost:8000/api/v1/storages?page=1',
  from: 1,
  last_page: 1,
  last_page_url: 'http://localhost:8000/api/v1/storages?page=1',
  next_page_url: null,
  path: 'http://localhost:8000/api/v1/storages',
  per_page: 15,
  prev_page_url: null,
  to: 5,
  total: 5
}

**Comment by H37kouya** [comment]
これ、APIを最新版にしてないからだ
