### ISSUE TITLE
自分の作品一覧(黒須)

### ISSUE THREAD

**Issue by toson77** [u-lab/rebuilt#39]
## URL
/users/storages/:storageId

**Comment by toson77** [comment]
アイコンのインポートってどうやるんだっけ
![image](https://user-images.githubusercontent.com/53248281/76829279-1ebee000-6866-11ea-901b-89258ae98003.png)

![image](https://user-images.githubusercontent.com/53248281/76829220-fc2cc700-6865-11ea-9921-91b77658146b.png)

**Comment by H37kouya** [comment]
#48 参照

**Comment by toson77** [comment]
アイコンjustify align center効かなーい
![image](https://user-images.githubusercontent.com/53248281/76831068-f20cc780-6869-11ea-8f70-bb6d03a0a15b.png)

**Comment by H37kouya** [comment]
> アイコンjustify align center効かなーい
> ![image](https://user-images.githubusercontent.com/53248281/76831068-f20cc780-6869-11ea-8f70-bb6d03a0a15b.png)

コード貼ってーー

**Comment by toson77** [comment]
こうやったら justify align 効いた
` <v-card
            :to="{
              name: 'users.storages.edit',
              params: { storageId: data.data[0].storage_id }
            }"
            color="
            #AED581"
            hover
          >
            <v-row align="center">
              <v-col
                align="end"
                cols="2"
              >
                <v-icon x-large>mdi-plus</v-icon>
              </v-col>
              <v-col cols="10">
                <v-card-title>test</v-card-title>
              </v-col>
            </v-row>
          </v-card>`
![image](https://user-images.githubusercontent.com/53248281/76832552-d951e100-686c-11ea-9b5d-e30ca78991ca.png)

**Comment by toson77** [comment]
v-card height指定すると変になる
![image](https://user-images.githubusercontent.com/53248281/76833428-af012300-686e-11ea-8a7b-e0666e71ab96.png)
