### ISSUE TITLE
Vuetify アイコンの使い方

### ISSUE THREAD

**Issue by H37kouya** [u-lab/rebuilt#48]
アイコンのインポートってどうやるんだっけ
![image](https://user-images.githubusercontent.com/53248281/76829279-1ebee000-6866-11ea-901b-89258ae98003.png)

![image](https://user-images.githubusercontent.com/53248281/76829220-fc2cc700-6865-11ea-9921-91b77658146b.png)

_Originally posted by @toson77 in https://github.com/u-lab/rebuilt/issues/39#issuecomment-599904369_

**Comment by H37kouya** [comment]
## 参考
https://vuetifyjs.com/ja/components/icons/

## 使い方
``` html
<template>
  <v-icon>アイコン名</v-icon>
</template>
```
mdiSvgを使いたいとすると
``` html
/* Example */
<template>
  <v-icon>mdi-svg</v-icon>
</template>
```

**Comment by toson77** [comment]
mdi-アイコン名ででてきた

**Comment by H37kouya** [comment]
@toson77 
一番上に書いてあるよ。
https://vuetifyjs.com/ja/components/icons/
<blockquote>
'v-icon' コンポーネントは、アプリケーションのさまざまな場面で使えるグリフの大規模なセットを提供します。利用可能なすべてのアイコンのリストについては、公式のMaterial Design Iconsページをご覧ください。これらのアイコンのいずれかを使用するには、単に 'mdi-' プレフィックスの後にアイコン名を付けて使用します。
</blockquote>
