### ISSUE TITLE
headerの三角の部分を作成する(/pages/:user)

### ISSUE THREAD

**Issue by H37kouya** [u-lab/rebuilt#53]
headerの右側の三角の部分を作成する

## やりかた

以下、２パターンが現状思いついている。

- 三角のpngを用意する
- CSSで作成する [参考にできそうな記事](https://www.granfairs.com/blog/staff/make-triangle-with-css)

## デザイン例：スクリーンショット
![コメント 2020-03-17 202053](https://user-images.githubusercontent.com/46477357/76851600-e2eb4100-688c-11ea-83a6-7f47ff00ed1b.png)

_Originally posted by @H37kouya in https://github.com/u-lab/rebuilt/issues/44#issuecomment-600016946_

**Comment by toson77** [comment]
これイラレか何かでheader全部作ってsvgで出力した方がよくない？

**Comment by toson77** [comment]
なぜー
![image](https://user-images.githubusercontent.com/53248281/77896642-8f78ea00-72b3-11ea-8d4d-566960185912.png)
![image](https://user-images.githubusercontent.com/53248281/77896686-9e5f9c80-72b3-11ea-8aa5-e30ea9d97e5e.png)

**Comment by toson77** [comment]
app.scssのimportの順番変えたらなおった
