### ISSUE TITLE
これまでの歴史のデザインをきれいにする

### ISSUE THREAD

**Issue by H37kouya** [u-lab/rebuilt#80]
## やること
これまでの歴史のデザインをきれいにする
空白を開けたり、色々やることがある。

## 対象ファイル
/user/page/edit

## スクリーンショット
![コメント 2020-04-03 175149](https://user-images.githubusercontent.com/46477357/78342265-f9ef9a00-75d3-11ea-93ad-dfce710a4e0a.png)
![コメント 2020-04-03 175138](https://user-images.githubusercontent.com/46477357/78342279-fbb95d80-75d3-11ea-8e74-c9b7cbc711fd.png)

**Comment by toson77** [comment]
わしやる
