### ISSUE TITLE
ログイン画面のサイドバーに対してt関数(i18n)を使用する

### ISSUE THREAD

**Issue by H37kouya** [u-lab/rebuilt#83]
# やること
/user/hoge系の画面でサイドバーを翻訳に対応させる。
翻訳が足りない場合は、langを新規追加すること。

## 対象ファイル
components/user/storages/Sidebar.vue

## スクリーンショット
![コメント 2020-04-03 181625](https://user-images.githubusercontent.com/46477357/78344367-3f619680-75d7-11ea-88d9-a02679708bd0.png)

**Comment by toson77** [comment]
あとでわしやる
